# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 5566a513-md-normal
  namespace: 5566a513
spec:
  template:
    spec: {}
